export const CHECK_CAPTCHA = 'CHECK_CAPTCHA'

export const CHANGE_LOGING_STATUS = 'CHANGE_LOGING_STATUS'

export const GET_NEWS_LISTS = 'GET_NEWS_LISTS'

export const GET_CATEGORIES = 'GET_CATEGORIES'

export const ADD_ARTICLE = 'ADD_ARTICLE'

export const DEL_NEWS = 'DEL_NEWS'

export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CREATE_CATEGORIES = 'CREATE_CATEGORIES'

export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'

export const DELETE_CATEGORIES = 'DELETE_CATEGORIES'